version: '3'
services:
  cassandra:
    image: cassandra:3.11.9
    container_name: cassandra
    ports:
    - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    restart: always

  cassandra-load-keyspace:
      container_name: cassandra-load-keyspace
      image: cassandra:3.11.9
      depends_on:
        - cassandra
      volumes:
        - ./src/main/resources/cassandra.cql:/schema.cql 
      command: /bin/bash -c "sleep 60 && echo loading cassandra keyspace && cqlsh cassandra -f /schema.cql"

  backend:
    build: .
    ports:
    - "6060:6060"
    volumes:
    - .:/robome-backend
    depends_on:
    - 'cassandra'
